-- MySQL Script generated by MySQL Workbench
-- Sat May 27 03:26:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Warehouses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Warehouses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Warehouses` DEFAULT CHARACTER SET utf8 ;
USE `Warehouses` ;


-- -----------------------------------------------------
-- Table `Warehouses`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`User` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `password` VARCHAR(20) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouses`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`Room` (
  `id_room` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `capacity` INT NULL,
  PRIMARY KEY (`id_room`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouses`.`Shelf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`Shelf` (
  `id_shelf` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `capacity` INT NULL,
  `room_id` INT NOT NULL,
  PRIMARY KEY (`id_shelf`),
    FOREIGN KEY (`room_id`)
    REFERENCES `Warehouses`.`Room`(`id_room`) ON DELETE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Warehouses`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`Product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NULL,
  `type` VARCHAR(120) NULL,
  `quantity` INT NULL,
  `shelf_id` INT NOT NULL,
  `contract_id` INT NOT NULL,
  PRIMARY KEY (`id_product`),
    FOREIGN KEY (`shelf_id`)
    REFERENCES `Warehouses`.`Shelf`(`id_shelf`) ON DELETE CASCADE,
    FOREIGN KEY (`contract_id`)
    REFERENCES `Warehouses`.`Contract`(`id_contract`) ON DELETE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Warehouses`.`Сontract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`Contract` (
  `id_contract` INT NOT NULL AUTO_INCREMENT,
  `startdate` date NULL,
  `number` INT NULL,
  `enddate` date NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id_contract`),
  FOREIGN KEY (`company_id`)
	REFERENCES `Warehouses`.`Company` (`id_company`) ON DELETE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Warehouses`.`Сontract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`Company` (
  `id_company` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `address` VARCHAR(100) NULL,
  `phone` VARCHAR(10) NULL,
  `tin` VARCHAR(10) NULL,
  PRIMARY KEY (`id_company`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
