-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 19:01:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WarehousesList
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WarehousesList
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WarehousesList` DEFAULT CHARACTER SET utf8 ;
USE `WarehousesList` ;

-- -----------------------------------------------------
-- Table `WarehousesList`.`Warehouses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WarehousesList`.`Warehouses` (
  `WarehouseID` INT NOT NULL,
  `Address` VARCHAR(256) NULL,
  PRIMARY KEY (`WarehouseID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
