-- MySQL Script generated by MySQL Workbench
-- Mon Feb 27 20:18:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Warehouses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Warehouses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Warehouses` DEFAULT CHARACTER SET utf8 ;
USE `Warehouses` ;

-- -----------------------------------------------------
-- Table `Warehouses`.`Warehouses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`Warehouses` (
  `idWarehouse` INT NOT NULL,
  `Address` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idWarehouse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouses`.`Managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`Managers` (
  `idManager` INT NOT NULL,
  `Name` VARCHAR(32) NOT NULL,
  `Surname` VARCHAR(32) NOT NULL,
  `WarehouseID` INT NOT NULL,
  PRIMARY KEY (`idManager`, `WarehouseID`),
  INDEX `fk_Manager_Warehouse1_idx` (`WarehouseID` ASC) VISIBLE,
  CONSTRAINT `fk_Manager_Warehouse1`
    FOREIGN KEY (`WarehouseID`)
    REFERENCES `Warehouses`.`Warehouses` (`idWarehouse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouses`.`Companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`Companies` (
  `idCompany` INT NOT NULL,
  `Name` VARCHAR(64) NOT NULL,
  `Address` VARCHAR(64) NOT NULL,
  `Phone number` VARCHAR(18) NOT NULL,
  `MSRN` VARCHAR(13) NOT NULL,
  `TIN` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idCompany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouses`.`Contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`Contracts` (
  `idContract` INT NOT NULL,
  `Start Date` DATE NOT NULL,
  `End Date` DATE NOT NULL,
  `WarehouseID` INT NOT NULL,
  `CompanyID` INT NOT NULL,
  PRIMARY KEY (`idContract`, `WarehouseID`, `CompanyID`),
  INDEX `fk_Contract_Warehouse1_idx` (`WarehouseID` ASC) VISIBLE,
  INDEX `fk_Contract_Company1_idx` (`CompanyID` ASC) VISIBLE,
  CONSTRAINT `fk_Contract_Warehouse1`
    FOREIGN KEY (`WarehouseID`)
    REFERENCES `Warehouses`.`Warehouses` (`idWarehouse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contract_Company1`
    FOREIGN KEY (`CompanyID`)
    REFERENCES `Warehouses`.`Companies` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouses`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`Rooms` (
  `idRoom` INT NOT NULL,
  `WarehouseID` INT NOT NULL,
  PRIMARY KEY (`idRoom`, `WarehouseID`),
  INDEX `fk_Room_Warehouse1_idx` (`WarehouseID` ASC) VISIBLE,
  CONSTRAINT `fk_Room_Warehouse1`
    FOREIGN KEY (`WarehouseID`)
    REFERENCES `Warehouses`.`Warehouses` (`idWarehouse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouses`.`Shelfs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`Shelfs` (
  `idShelf` INT NOT NULL,
  `Capacity` FLOAT NOT NULL,
  `RoomID` INT NOT NULL,
  PRIMARY KEY (`idShelf`),
  INDEX `fk_Shelf_Room_idx` (`RoomID` ASC) VISIBLE,
  CONSTRAINT `fk_Shelf_Room`
    FOREIGN KEY (`RoomID`)
    REFERENCES `Warehouses`.`Rooms` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouses`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouses`.`Products` (
  `idProduct` INT NOT NULL,
  `Name` VARCHAR(32) NOT NULL,
  `Type` VARCHAR(32) NOT NULL,
  `ShelfID` INT NOT NULL,
  `CompanyID` INT NOT NULL,
  PRIMARY KEY (`idProduct`, `CompanyID`),
  INDEX `fk_Product_Shelf1_idx` (`ShelfID` ASC) VISIBLE,
  INDEX `fk_Product_Company1_idx` (`CompanyID` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Shelf1`
    FOREIGN KEY (`ShelfID`)
    REFERENCES `Warehouses`.`Shelfs` (`idShelf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Company1`
    FOREIGN KEY (`CompanyID`)
    REFERENCES `Warehouses`.`Companies` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
